import LogoLight from "@shared/app_icons/coffeeroll-logo.svg?react";
import LogoDark from "@shared/app_icons/coffeeroll-logo-dark.svg?react";
import { useNavigate } from "react-router-dom";

const NavbarLogo = () => {
  const navigate = useNavigate();
  const toRoot = () => navigate("/");
  // NOTE: IDK WTF IS THIS, IT'S GENERATED BY AI, BUT IT WORKS
  return (
    <div onClick={toRoot} className="flex justify-center cursor-pointer">
      <div className="hidden [html[data-theme=light]_&]:block">
        <LogoLight className="w-37 h-10" />
      </div>

      <div className="hidden [html[data-theme=dark]_&]:block">
        <LogoDark className="w-37 h-10" />
      </div>
    </div>
  );
};

export default NavbarLogo;
